# Generated by Django 3.2.3 on 2021-05-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
